# config/app.yml for rails-settings-cached
#
# This file contains default values, and does not need to be edited
# when configuring an instance.  These settings may be changed by an
# Administrator using the Web UI.
#
defaults: &defaults
  site_title: Hiveway
  site_description: 'Hiveway is to become a direct democratic social network, running fully autonomously. Its users will be able to post and interact with messages, photos and videos. The social platform will be ruled by its users, through an electoral system, with technocratic values.  The users will receive the right to vote on the development of the platform, to run for a position in managing it, and to vote the candidates they believe more competent for each position.'
  site_extended_description: ''
  site_terms: ''
  site_contact_username: '@hiveway'
  site_contact_email: 'contact@hiveway.io'
  open_registrations: true
  closed_registrations_message: ''
  open_deletion: true
  min_invite_role: 'admin'
  timeline_preview: true
  show_staff_badge: true
  default_sensitive: false
  unfollow_modal: false
  boost_modal: false
  delete_modal: true
  auto_play_gif: false
  reduce_motion: false
  system_font_ui: false
  noindex: false
  theme: 'default'
  notification_emails:
    follow: false
    reblog: false
    favourite: false
    mention: false
    follow_request: true
    digest: true
  interactions:
    must_be_follower: false
    must_be_following: false
    must_be_following_dm: false
  reserved_usernames:
    - admin
    - support
    - help
    - root
    - webmaster
    - administrator
  bootstrap_timeline_accounts: ''
  activity_api_enabled: true
  peers_api_enabled: true
  eth_rpc_node: 'http://172.17.172.114:8545'
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
